---
taps:
  - homebrew/cask
  - homebrew/cask-versions
  - soracom/soracom-cli

packages:
  - { name: ansible, state: present }
  - { name: awscli, state: present }
  - { name: git, state: present }
  - { name: jq, state: present }
  - { name: mas, state: present } # mas-cli(mac apple store)
  - { name: tree, state: present }
  - { name: guetzli, state: present }
  - { name: neovim, state: present }
  - { name: nkf, state: present }
  - { name: ag, state: present }
  - { name: soracom-cli, state: present }
  - { name: bash-completion, state: present }
  - { name: hub, state: present }
  - { name: ffmpeg, state: present }
